services:
  player-1:
    build: .
    environment:
      APP_OPPONENT_ADDRESS: player-2
      APP_TURN_DELAY_MS: 500
    ports:
      - "8081:8080" # REST
      - "9091:9090" # GRPC
  player-2:
    build: .
    environment:
      APP_OPPONENT_ADDRESS: player-1
      APP_TURN_DELAY_MS: 500
    ports:
      - "8082:8080" # REST
      - "9092:9090" # GRPC